### PR TITLE
Fix for next 15.2 and renderHTML should not be called in minimal mode

### LINKED ISSUE #432: [BUG] next 15.2.0 breaks non static routes
### Describe the bug

I've upgraded my app to next 15.2.0 and now i'm getting a 500 on some routes.

From a quick check it seems to only happen on the routes that don't use `generateStaticParams`

```
✘ [ERROR] ⨯ Error: Invariant: renderHTML should not be called in minimal mode

      at Object.renderHTMLImpl
  (/path/to/proj/.wrangler/tmp/dev-Cd8zgp/worker.js)
      at <unknown>
  (/path/to/proj/.wrangler/tmp/dev-Cd8zgp/worker.js)
      at Object.trace
  (/path/to/proj/.wrangler/tmp/dev-Cd8zgp/worker.js)
      at Object.renderHTML
  (/path/to/proj/.wrangler/tmp/dev-Cd8zgp/worker.js)
      at doRender
  (/path/to/proj/.wrangler/tmp/dev-Cd8zgp/worker.js)
      at responseGenerator
  (/path/to/proj/.wrangler/tmp/dev-Cd8zgp/worker.js)
      at Object.get
  (/path/to/proj/.wrangler/tmp/dev-Cd8zgp/worker.js)
      at Object.renderToResponseWithComponentsImpl
```

Versions of opennext/next/vercel:

```
"next": "^15.2.0",
"@opennextjs/aws": "^3.5.0",
"@opennextjs/cloudflare": "^0.5.7",
"vercel": "^41.3.0",
```

### Steps to reproduce

1. create a route without `generateStaticParams`
2. run `opennextjs-cloudflare && wrangler dev`
3. open in browser and see error 500

### Expected behavior

1. no 500 should be thrown for non static routes

### @opennextjs/cloudflare version

0.5.7

### Wrangler version

3.111.0

### next info output

```shell
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP PREEMPT_DYNAMIC Thu, 27 Feb 2025 18:09:44 +0000
  Available memory (MB): 31302
  Available CPU cores: 16
Binaries:
  Node: 20.18.2
  npm: 10.8.2
  Yarn: 1.22.19
  pnpm: 10.1.0
Relevant Packages:
  next: 15.2.0 // Latest available version is detected (15.2.0).
  eslint-config-next: 15.2.0
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.8.2
Next.js Config:
  output: N/A
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by conico974**
Should fix #432 #373 and #333

Next 15.2 introduced a change that create an `AbortController` https://github.com/vercel/next.js/pull/73975/files as a const outside of the request context.
This `AbortController` cause an issue while requiring app router pages that makes all these require return `{}` instead of the actual module in workerd. (see the comment for more detail)

It also replace the define of `process.env.NEXT_MINIMAL` inside of esbuild by a custom plugin that keep the `renderHTML` that can be used as a fallback by Next in case of error.

It also bump next version to 15.2.0 for the e2e examples

It's a draft for now, if workerd is not expected to throw for this case we could remove almost everything in this PR and just bump wrangler once fixed and merged

### CODE REVIEW

File: packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts [hunk 1]
```diff
@@ -0,0 +1,92 @@
+import { patchCode } from "../ast/util.js";
+import { ContentUpdater } from "./content-updater.js";
+
+// We try to be as specific as possible to avoid patching the wrong thing here
+// It seems that there is a bug in the worker runtime. When the AbortController is created outside of the request context it throws an error (not sure if it's expected or not) except in this case.
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts:5]: Workers can not do IO outside of the the request - there should be a clear error message in this case (and it should be easy enough to try outside of the context of Next).

Note that we also plan to not run any Next code oustide of a request context which should also help here.

File: packages/cloudflare/src/cli/build/patches/plugins/next-minimal.spec.ts [hunk 2]
```diff
@@ -0,0 +1,76 @@
+import { describe, expect, test } from "vitest";
+
+import { patchCode } from "../ast/util";
+import { abortControllerRule } from "./next-minimal";
+
+const appPageRuntimeProdJs = `let p = new AbortController;
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/next-minimal.spec.ts:6]: Do we need to have test for both plain an minified code? (i.e. does this code change whether debug is enabled?)

File: pnpm-workspace.yaml [hunk 3]
```diff
@@ -42,7 +42,7 @@ catalogs:
     "@types/react-dom": 19.0.0
     "@types/react": 19.0.0
     autoprefixer: 10.4.15
-    next: 15.1.0
+    next: 15.2.0
```
Comment (vicb) [inline pnpm-workspace.yaml:45]: question: what ex is using that?

File: packages/cloudflare/src/cli/build/bundle-server.ts [hunk 4]
```diff
@@ -136,7 +138,8 @@ export async function bundleServer(buildOpts: BuildOptions): Promise<void> {
       // We make sure that environment variables that Next.js expects are properly defined
       "process.env.NEXT_RUNTIME": '"nodejs"',
       "process.env.NODE_ENV": '"production"',
-      "process.env.NEXT_MINIMAL": "true",
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/bundle-server.ts:139]: Does that affect the bundle size (`pnpm wrangler dev --dry-run`)?

**Review by vicb — COMMENTED** [review]
Thanks @conico974 for this fix.

I think the workerd error is expected - but we should fix this by not running next code at top level. It will also help with other issues (access `process.env` and `getCloudflareContext()` at top level). I hope to get to this next week. But it should not be a reason not to merge this PR. 

I have added a few questions/comments after a quick review.

File: packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts (hunk 1 above)
Comment (conico974) [reply packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts:5]: Yeah, but in this case this is not actually doing any IO. Just creating an `AbortController` outside of the request context will trigger the error as described here https://github.com/cloudflare/workerd/issues/3657

It's the import of Next itself in this case that is causing trouble. I haven't found why it fails silently in this case

File: packages/cloudflare/src/cli/build/patches/plugins/next-minimal.spec.ts (hunk 2 above)
Comment (conico974) [reply packages/cloudflare/src/cli/build/patches/plugins/next-minimal.spec.ts:6]: No it is only a problem in the already minified `app-page.runtime.prod.js` or `app-page-experimental.runtime.prod.js`

File: pnpm-workspace.yaml (hunk 3 above)
Comment (conico974) [reply pnpm-workspace.yaml:45]: Only the e2e from aws if i'm not mistaken

File: packages/cloudflare/src/cli/build/bundle-server.ts (hunk 4 above)
Comment (conico974) [reply packages/cloudflare/src/cli/build/bundle-server.ts:139]: I was wrong actually, we need to define `__NEXT_EXPERIMENTAL_REACT`, otherwise it will bundle 2 versions of react and 2 versions of `app-page.runtime.prod.js` and `app-route.runtime.prod.js`. I've also checked and it should not cause any issue defining that for Next 14.2+.

On the app router e2e examples without the define, it's 800kb more unzipped, with it it's 1kb more (compared to defining `NEXT_MINIMAL`)

File: packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts (hunk 1 above)
Comment (vicb) [reply packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts:5]: Thanks a lot for creating the issue!

FYI The service worker syntax is deprecated

```ts
addEventListener("fetch", event => {
  event.respondWith(new Response("Hello World"));
});
```

See https://developers.cloudflare.com/workers/reference/migrate-to-module-workers

File: pnpm-workspace.yaml (hunk 3 above)
Comment (vicb) [reply pnpm-workspace.yaml:45]: I missed that it was on the e2e catalog, looks fine!

File: packages/cloudflare/src/cli/build/bundle-server.ts [hunk 5]
```diff
@@ -136,7 +138,9 @@ export async function bundleServer(buildOpts: BuildOptions): Promise<void> {
...
+      "process.env.TURBOPACK": "false",
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/bundle-server.ts:141]: can you add comments explaining the effect of `TURBOPACK` and `_NEXT_EXPERIMENTAL_REACT`?
Thanks!

**Review by vicb — APPROVED** [review]
Awesome PR, it will be well appreciated by the community 🎉

I have added a few minor comments

File: packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts [hunk 6]
```diff
@@ -0,0 +1,92 @@
...
+        kind: function_declaration
+        stopBy: end
+        has:
+          kind: statement_block
+          has:
+            kind: try_statement
+            has:
+              kind: catch_clause
+              has:
+                kind: statement_block
```
[the remark this answers is not in the document]
Comment (conico974) [reply packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts:23]: Probably not, but as i said in the comment i just wanted to be extra careful on this one, this is a precompiled file and we want to target a `var a = new AbortController();`. This way it follows exactly the ast

[the remark this answers is not in the document]
Comment (vicb) [reply packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts:23]: Keeping a function declaration with the constraint on the return statement should be enough?
But ok to keep all if you think it's worth.

[the remark this answers is not in the document]
Comment (conico974) [reply packages/cloudflare/src/cli/build/patches/plugins/next-minimal.ts:23]: Better be safe than sorry :wink:
