### PR TITLE
fix: Windows support

### LINKED ISSUE #59: Build, Preview, and Deployment are not functioning on Windows
This is what I get when I run : `yarn run preview`  or `npm run preview`

### package.json
```
{
  "name": "my-next-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "deploy": "cloudflare && wrangler deploy",
    "preview": "cloudflare && wrangler dev",
    "cf-typegen": "wrangler types --env-interface CloudflareEnv env.d.ts",
    "dev:worker": "wrangler dev --port 3000"
  },
  "dependencies": {
    "next": "14.2.5",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20240925.0",
    "@opennextjs/cloudflare": "^0.0.0-59a1d9e",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.5",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5",
    "wrangler": "^3.79.0"
  }
}
```

### Error Log
```
yarn run preview
yarn run v1.22.21
$ cloudflare && wrangler dev
Building the Next.js app in the current folder (E:\testing\next-cloudflare-KV\KVApp)
$ E:\testing\next-cloudflare-KV\KVApp\node_modules\.bin\next build
 ⚠ Invalid next.config.mjs options detected:
 ⚠     Unrecognized key(s) in object: 'skipTrailingSlashRedirects'
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
  ▲ Next.js 14.2.5

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
 ✓ Generating static pages (6/6)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ ○ /                                    5.25 kB        92.3 kB
├ ○ /_not-found                          871 B          87.9 kB
├ ƒ /api/cache                           0 B                0 B
└ ƒ /dynamic                             136 B          87.2 kB
+ First Load JS shared by all            87 kB
  ├ chunks/23-7b0d78b6b8bdf59e.js        31.5 kB
  ├ chunks/fd9d1056-2821b0f0cabcd8bd.js  53.6 kB
  └ other shared chunks (total)          1.86 kB


○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand

⚙️ Copying files...

# copyPackageTemplateFiles
⚙️ Bundling the worker file...

# patchWranglerDeps
# updateWebpackChunksFile
 - chunk 349.js
 - chunk 621.js
 - chunk 682.js
 - chunk 948.js
# patchRequire
# patchReadFile
# inlineNextRequire
# patchFindDir
# inlineEvalManifest
# patchCached
Worker saved in `E:\testing\next-cloudflare-KV\KVApp\.worker-next\index.mjs` 🚀


 ⛅️ wrangler 3.80.0
-------------------

Your worker has access to the following bindings:
- KV Namespaces:
  - NEXT_CACHE_WORKERS_KV: de27e0b7d3c44bd48308b4e42df1ccd0
[wrangler:inf] Ready on http://127.0.0.1:8787
╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│  [b] open a browser, [d] open devtools, [l] turn off local mode, [c] clear console, [x] to exit  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
✘ [ERROR] Could not resolve "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverpages_app.js"

    .worker-next/index.mjs:25029:27:
      25029 │ ...n require("E:\testing\next-cloudflare-KV\KVApp\.worker-next\...
            ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverpages_app.js" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverpages_error.js"

    .worker-next/index.mjs:25034:27:
      25034 │ ...n require("E:\testing\next-cloudflare-KV\KVApp\.worker-next\...
            ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverpages_error.js" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverpages_document.js"

    .worker-next/index.mjs:25039:27:
      25039 │ ...n require("E:\testing\next-cloudflare-KV\KVApp\.worker-next\...
            ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverpages_document.js" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverapp_not-foundpage.js"

    .worker-next/index.mjs:25044:27:
      25044 │ ...n require("E:\testing\next-cloudflare-KV\KVApp\.worker-next\...
            ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverapp_not-foundpage.js" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverapp\favicon.ico\route.js"

    .worker-next/index.mjs:25049:27:
      25049 │ ...n require("E:\testing\next-cloudflare-KV\KVApp\.worker-next\...
            ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverapp\favicon.ico\route.js" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverapppage.js"

    .worker-next/index.mjs:25054:27:
      25054 │ ...n require("E:\testing\next-cloudflare-KV\KVApp\.worker-next\...
            ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverapppage.js" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverappdynamicpage.js"

    .worker-next/index.mjs:25059:27:
      25059 │ ...n require("E:\testing\next-cloudflare-KV\KVApp\.worker-next\...
            ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverappdynamicpage.js" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverappapicache\route.js"

    .worker-next/index.mjs:25064:27:
      25064 │ ...n require("E:\testing\next-cloudflare-KV\KVApp\.worker-next\...
            ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone.nextserverappapicache\route.js" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone\node_modules@opennextjscloudflareclicache-handler.mjs"

    .worker-next/index.mjs:30495:29:
      30495 │ ...it import('E:\testing\next-cloudflare-KV\KVApp\.worker-next\...
            ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "E:\testing\next-cloudflare-KVKVApp.worker-next.nextstandalone\node_modules@opennextjscloudflareclicache-handler.mjs" as external to exclude it from the bundle, which will remo

✘ [ERROR] Failed to build


╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│  [b] open a browser, [d] open devtools, [l] turn off local mode, [c] clear console, [x] to exit  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
√ Would you like to report this error to Cloudflare? ... yes
🪵  Logs were written to "C:\Users\parvesh\AppData\Roaming\xdg.config\.wrangler\logs\wrangler-2024-10-04_12-27-27_208.log"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### PR DESCRIPTION
**Pull request by clansty**
fix #59

### CODE REVIEW

File: packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts [hunk 1]
```diff
@@ -13,7 +13,9 @@ export function inlineEvalManifest(code: string, config: Config): string {
   console.log("# inlineEvalManifest");
   const manifestJss = globSync(
     path.join(config.paths.standaloneAppDotNext, "**", "*_client-reference-manifest.js").replaceAll("\\", "/")
-  ).map((file) => file.replaceAll("\\", "/").replace(`${config.paths.standaloneApp.replaceAll("\\", "/")}/`, ""));
+  ).map((file) =>
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts:16]: maybe a cleaner way to fix this would be to 
- use `.replaceAll(path.sep, path.posix.sep)`
- move that in an helper function
- apply that everywhere we have path, i.e. here and where `config.paths...` are set

**Review by vicb — CHANGES_REQUESTED** [review]
Thanks for fixing this.

Would you mind looking at the suggestion in the comment?

File: packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts (hunk 1 above)
Comment (clansty) [reply packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts:16]: > apply that everywhere we have path, i.e. here and where `config.paths...` are set

I think there may be side effects if we apply this everywhere

It's just something wrong with `glob`

Comment (clansty) [reply packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts:18]: I have now replaced with `.replaceAll(path.sep, path.posix.sep)`

I think `value.replace...` is better than `fixPath(value)` because we don't need to wrap the `value` here in `()`, and if we want to create an extension method we need to use `String.prototype...`

Comment (james-elicx) [reply packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts:18]: I think extracting the (...).replaceAll(..., ...) to a function like normalizePath(...) would be beneficial. It would save us from having to write the same replace each time, and can then just use a function where it cares about the specifics internally.

If I think back to how we handled this in [next-on-pages](https://github.com/cloudflare/next-on-pages/blob/96c331d20e679ebad0e43153430786685dbbcdec/packages/next-on-pages/src/utils/fs.ts#L27), we were also accounting for extended-length paths on windows as well as part of that function. Maybe something to consider here too?

Comment (vicb) [reply packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts:18]: > I think extracting the (...).replaceAll(..., ...) to a function like normalizePath(...) would be beneficial.

+1 to that

And you can use `path.posix.sep` l21:

```js
.replace(config.paths.standaloneApp.replaceAll(path.sep, path.posix.sep) + path.posix.sep, "")
```

Thanks!

Comment (clansty) [reply packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts:18]: > And you can use `path.posix.sep` l21:
> 
> ```js
> .replace(config.paths.standaloneApp.replaceAll(path.sep, path.posix.sep) + path.posix.sep, "")
> ```

Real

Comment (clansty) [reply packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts:18]: > I think extracting the (...).replaceAll(..., ...) to a function like normalizePath(...) would be beneficial. It would save us from having to write the same replace each time, and can then just use a function where it cares about the specifics internally.

I think it may not be called `normalizePath` because something like `C:/Windows` does not seem normal on Windows

File: packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts [hunk 2]
```diff
@@ -12,16 +12,22 @@ import path from "node:path";
...
   const manifestJss = globSync(
-    path.join(config.paths.standaloneAppDotNext, "**", "*_client-reference-manifest.js")
-  ).map((file) => file.replace(`${config.paths.standaloneApp}/`, ""));
+    path
+      .join(config.paths.standaloneAppDotNext, "**", "*_client-reference-manifest.js")
+      .replaceAll(path.sep, path.posix.sep)
+  ).map((file) =>
+    file
+      .replaceAll(path.sep, path.posix.sep)
+      .replace(`${config.paths.standaloneApp.replaceAll(path.sep, path.posix.sep)}/`, "")
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts:21]:
```suggestion
      .replace(config.paths.standaloneApp.replaceAll(path.sep, path.posix.sep) + path.posix.sep, "")
```

File: packages/cloudflare/src/cli/build/patches/to-investigate/patch-read-file.ts [hunk 3]
```diff
@@ -16,11 +16,15 @@ export function patchReadFile(code: string, config: Config): string {
...
   // (source: https://github.com/vercel/next.js/blob/15aeb92e/packages/next/src/server/load-manifest.ts#L34-L56)
   // Note: we could/should probably just patch readFileSync here or something!
-  const manifestJsons = globSync(path.join(config.paths.standaloneAppDotNext, "**", "*-manifest.json")).map(
-    (file) => file.replace(config.paths.standaloneApp + "/", "")
+  const manifestJsons = globSync(
+    path.join(config.paths.standaloneAppDotNext, "**", "*-manifest.json").replaceAll(path.sep, path.posix.sep)
+  ).map((file) =>
+    file
+      .replaceAll(path.sep, path.posix.sep)
+      .replace(config.paths.standaloneApp.replaceAll(path.sep, path.posix.sep) + "/", "")
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/to-investigate/patch-read-file.ts:27]:
```suggestion
      .replace(config.paths.standaloneApp.replaceAll(path.sep, path.posix.sep) + path.posix.sep, "")
```

File: packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts (hunk 1 above)
Comment (vicb) [reply packages/cloudflare/src/cli/build/patches/to-investigate/inline-eval-manifest.ts:18]: normalize is a common term to refer to the process of converting different inputs to a common format. But let's defer that to a follow up PR and merge this one to unblock normal WIndows users ;)

**Review by vicb — APPROVED** [review]
