### PR TITLE
Fix exports and imports for package.json for workerd

### LINKED ISSUE #623: [BUG] Prisma throws `Error: [unenv] fs.readdir is not implemented yet!` when querying
### Describe the bug

After following the [Cloudflare workers with PostgreSQL tutorial](https://www.prisma.io/docs/orm/prisma-client/deployment/edge/deploy-to-cloudflare#postgresql-traditional).

When making a query via prisma client `Error: [unenv] fs.readdir is not implemented yet!` is thrown when running via the workers runtime `pnpm preview`.

When using a worker directly, Prisma works correctly.

```prisma
// schema.prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id        Int      @id @default(autoincrement())
  title     String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
```

```tsx
// page.tsx
export default async function Home() {
  
// Force SSR
  connection();

  const connectionString = "example"

  const adapter = new PrismaPg({ connectionString });
  const prisma = new PrismaClient({ adapter });

  const posts = await prisma.post.findMany();
  return (
    <div>
      <div>{Date()}</div>
      <div>{JSON.stringify(posts)}</div>
    </div>
  );
} 
```

Image

### Steps to reproduce

1. Clone the [minimal reproduction](https://github.com/schweetheart/opennext-prisma-example)
2. Set `DATABASE_URL` in .env and .dev.vars with a postgres compatible database. (I used [Neon](https://neon.tech/))
3. Preview the app locally via `pnpm preview`
4. Visit `http://localhost:3000/`
5. You should see the error in the dialog.

### Expected behavior

 When [running prisma directly in a worker](https://github.com/schweetheart/prisma-cloudflare-worker-example) **without** OpenNext, with the same code the result is working. When running the same code with OpenNext, the error is thrown.
Am I missing some configuration, or is there some unexpected behavior when the OpenNext build process interacts with Prisma.

### @opennextjs/cloudflare version

1.0.0-beta.4

### Wrangler version

4.14.0

### next info output

```shell
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.4.0: Fri Apr 11 18:33:47 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6000
  Available memory (MB): 16384
  Available CPU cores: 8
Binaries:
  Node: 20.11.1
  npm: 10.8.1
  Yarn: 1.22.19
  pnpm: 9.15.0
Relevant Packages:
  next: 15.3.1 // Latest available version is detected (15.3.1).
  eslint-config-next: 15.3.1
  react: 19.1.0
  react-dom: 19.1.0
  typescript: 5.8.3
Next.js Config:
  output: N/A
```

### Additional context

Setting `PRISMA_CLIENT_FORCE_WASM=1` has had no effect. I also tested via the `@prisma/adapter-neon` adapter with the same error.

It looks like[ others have encountered the same error](https://github.com/prisma/prisma/discussions/27041) recently with different adapters.

### PR DESCRIPTION
**Pull request by conico974**
Remove other exports and imports (than workerd) when found in package.json. This fix an issue with build conditions order in esbuild because we use `platform:node`
It also fix an issue with wasm file not properly working if imported without `?module`
Fix #623

### CODE REVIEW

File: packages/cloudflare/src/cli/build/patches/plugins/wrangler-external.ts [hunk 1]
```diff
@@ -25,7 +25,8 @@ export function setWranglerExternal() {
     setup: async (build: PluginBuild) => {
       const namespace = "wrangler-externals-plugin";
 
-      build.onResolve({ filter: /(\.bin|\.wasm\?module)$/ }, ({ path, importer }) => {
+      //TODO: Ideally in the future we would like to analyze the files in case they are using wasm in a Node way (i.e. WebAssembly.instantiate)
+      build.onResolve({ filter: /(\.bin|\.wasm(\?module))$/ }, ({ path, importer }) => {
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/wrangler-external.ts:29]: Note: there is no functional change on this line, intended?

Comment (conico974) [reply packages/cloudflare/src/cli/build/patches/plugins/wrangler-external.ts:29]: Nope, i forgot a `?`

Comment (vicb) [reply packages/cloudflare/src/cli/build/patches/plugins/wrangler-external.ts]: i.e. missing `?`

File: packages/cloudflare/src/cli/build/utils/workerd.ts [hunk 2]
```diff
@@ -7,27 +7,67 @@ import logger from "@opennextjs/aws/logger.js";
...
 
 /**
- * Return whether the passed export map has the given condition
+ * This function transforms the exports (or imports) object from the package.json
+ * to only include the build condition if found (e.g. "workerd") and remove everything else.
+ * If no build condition is found, it keeps everything as is.
+ * It also returns a boolean indicating if the build condition was found.
+ * @param exports The exports (or imports) object from the package.json
+ * @param condition The build condition to look for
+ * @returns An object with the transformed exports and a boolean indicating if the build condition was found
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/utils/workerd.ts:16]: suggestion: add an explicit return type?

File: packages/cloudflare/src/cli/build/utils/workerd.ts [hunk 3]
```diff
@@ -7,27 +7,67 @@ import logger from "@opennextjs/aws/logger.js";
...
  */
-export function hasBuildCondition(
-  exports: { [key: string]: unknown } | undefined,
-  condition: string
-): boolean {
-  if (!exports) {
-    return false;
-  }
+export function transformBuildCondition(exports: { [key: string]: unknown }, condition: string) {
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/utils/workerd.ts:18]: suggestion: `exports` -> `condition map` ?

File: packages/cloudflare/src/cli/build/utils/workerd.ts [hunk 4]
```diff
@@ -7,27 +7,67 @@ import logger from "@opennextjs/aws/logger.js";
...
+  imports?: { [key: string]: unknown };
+}
+
+/**
+ *
+ * @param json The package.json object
+ * @returns An object with the transformed package.json and a boolean indicating if the build condition was found
+ */
+export function transformPackageJson(json: PackageJson) {
+  const transformed: PackageJson = { ...json };
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/utils/workerd.ts:58]: `{...json}` does not really help here as we are updating objects -> `structureClone`?

File: packages/cloudflare/src/cli/build/utils/workerd.ts [hunk 5]
```diff
@@ -7,27 +7,67 @@ import logger from "@opennextjs/aws/logger.js";
...
     if (typeof value === "object" && value != null) {
-      if (hasBuildCondition(value as { [key: string]: unknown }, condition)) {
-        return true;
-      }
+      const { transformedExports, hasBuildCondition: innerBuildCondition } = transformBuildCondition(
+        value as { [key: string]: unknown },
+        condition
+      );
+      transformed[key] = transformedExports;
+      hasBuildCondition = hasBuildCondition || innerBuildCondition;
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/utils/workerd.ts:31]:
```suggestion
      hasBuildCondition ||= innerBuildCondition;
```

File: packages/cloudflare/src/cli/build/utils/workerd.ts [hunk 6]
```diff
@@ -7,27 +7,67 @@ import logger from "@opennextjs/aws/logger.js";
...
+ * @param json The package.json object
+ * @returns An object with the transformed package.json and a boolean indicating if the build condition was found
+ */
+export function transformPackageJson(json: PackageJson) {
+  const transformed: PackageJson = { ...json };
+  let hasBuildCondition = false;
+  if (json.exports) {
+    const exp = transformBuildCondition(json.exports, "workerd");
+    transformed.exports = exp.transformedExports;
+    hasBuildCondition = exp.hasBuildCondition;
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/utils/workerd.ts:63]: consistency
```suggestion
    hasBuildCondition ||= exp.hasBuildCondition;
```

File: packages/cloudflare/src/cli/build/utils/workerd.ts [hunk 7]
```diff
@@ -7,27 +7,67 @@ import logger from "@opennextjs/aws/logger.js";
...
+  }
+  if (json.imports) {
+    const imp = transformBuildCondition(json.imports, "workerd");
+    transformed.imports = imp.transformedExports;
+    hasBuildCondition = hasBuildCondition || imp.hasBuildCondition;
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/utils/workerd.ts:68]:
```suggestion
    hasBuildCondition ||= imp.hasBuildCondition;
```

File: packages/cloudflare/src/cli/build/utils/workerd.ts [hunk 8]
```diff
@@ -38,17 +78,16 @@ export async function copyWorkerdPackages(options: BuildOptions, nodePackages: M
...
-        externalPackages.includes(match.groups.pkg) &&
-        hasBuildCondition(exports, "workerd")
-      ) {
+      if (match?.groups?.pkg && externalPackages.includes(match.groups.pkg) && hasBuildCondition) {
         logger.debug(
           `Copying package using a workerd condition: ${path.relative(options.appPath, src)} -> ${path.relative(options.appPath, dst)}`
         );
-        fs.cp(src, dst, { recursive: true, force: true });
+        await fs.cp(src, dst, { recursive: true, force: true });
+        // Write the transformed package.json
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/utils/workerd.ts:89]:
```suggestion
        // Overwrite with the transformed package.json
```

**Review by vicb — APPROVED** [review]
Thanks!

Great that this will enable prisma 🎉

**Comment by lujjjh** [comment]
Thanks for your contribution. While trying to use the main branch to fix the Sentry import issue (#587), I noticed that Sentry’s exports are not treated as `hasBuildCondition`:

https://github.com/getsentry/sentry-javascript/blob/eb495521e94f7808b26db5dc7e9c2f290fee6141/packages/nextjs/package.json#L18-L48

After checking the spec, it seems this is by design?

https://github.com/opennextjs/opennextjs-cloudflare/blob/a169b7669544a26f1b66cf9d5061b554d2f09edc/packages/cloudflare/src/cli/build/utils/workerd.spec.ts#L83-L95

**Comment by vicb** [comment]
I think OpenNext is correct here:

[getsentry/sentry-javascript@eb49552/packages/nextjs/package.json#L18-L48](https://github.com/getsentry/sentry-javascript/blob/eb495521e94f7808b26db5dc7e9c2f290fee6141/packages/nextjs/package.json#L18-L48) has

```json
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "types": "./build/types/index.types.d.ts",
      // ...
      "workerd": {
        "import": "./build/esm/edge/index.js",
        "require": "./build/cjs/edge/index.js",
        "default": "./build/esm/edge/index.js"
      },
```

**Comment by lujjjh** [comment]
> `workerd` looks to be a path here and the conditions are `import`, `require`, and `default`

After reading the [nested conditions](https://nodejs.org/api/packages.html#nested-conditions) section, I believe this should be interpreted as a case of nested conditions.

And `workerd` cannot be a path here because:

> All paths defined in the "exports" must be relative file URLs starting with `./.`

Meanwhile:

> In node, conditions have very few restrictions, but specifically these include: [...]
> 2. They cannot start with "." since they may appear in places that also allow relative paths.

---

I'm also unsure whether this nested spec is valid:

https://github.com/opennextjs/opennextjs-cloudflare/blob/a169b7669544a26f1b66cf9d5061b554d2f09edc/packages/cloudflare/src/cli/build/utils/workerd.spec.ts#L31-L41

According to the documentation, it seems that only "nested conditions" are supported, not "nested paths?" Or, maybe this usage is documented somewhere else, but I haven’t come across it.

**Comment by Noitidart** [comment]
I tried `npm i https://pkg.pr.new/@opennextjs/cloudflare@628` but this didn't fix the issue for me.

**Comment by Noitidart** [comment]
I have shared a minimum repro here - https://github.com/opennextjs/opennextjs-cloudflare/issues/623#issuecomment-2974057104
