### PR TITLE
make sure that instrumentation files work

### LINKED ISSUE #171: Investigate and support Next.js instrumentation
Next.js 15 introduced a `loadInstrumentationModule` methods that appears in our bundled worker which caused our workers to fail at runtime.

We're solved such issue by replacing the content of the `loadInstrumentationModule` methods with a no-op implementation (see: https://github.com/opennextjs/opennextjs-cloudflare/pull/169), this was the simplest and quickest way to work around the issue and unblock Next.js 15 for us, it is however most likely not the correct solution and almost certainly breaks [Next.js' instrumentation](https://nextjs.org/docs/app/building-your-application/optimizing/instrumentation).
 
So this issue is for investigating and understanding if and how we support instrumentation, and if we don't support it (which most likely we don't) find a way to do so.

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
fixes #171

### CODE REVIEW

File: examples/common/apps.ts [hunk 1]
```diff
@@ -7,6 +7,7 @@ const apps = [
   "vercel-blog-starter",
   "vercel-commerce",
   "ssg-app",
+  "instrumentation-app",
```
Comment (vicb) [inline examples/common/apps.ts:10]: Is there a particular reason to add an app instead of re-using i.e. the playground?

File: examples/middleware/tsconfig.json [hunk 2]
```diff
@@ -21,5 +21,5 @@
     ]
   },
   "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
-  "exclude": ["node_modules", "open-next.config.ts", "worker.ts"]
+  "exclude": ["node_modules"]
```
Comment (vicb) [inline examples/middleware/tsconfig.json:24]: question: why is this file and its permission updated?

File: packages/cloudflare/src/cli/build/patches/plugins/load-instrumentation.ts [hunk 3]
```diff
@@ -2,23 +2,46 @@
...
+export function patchLoadInstrumentation(updater: ContentUpdater, buildOpts: BuildOptions) {
   return updater.updateContent(
     "patch-load-instrumentation",
     { filter: /\.(js|mjs|cjs|jsx|ts|tsx)$/, contentFilter: /async loadInstrumentationModule\(/ },
-    ({ contents }) => patchCode(contents, instrumentationRule)
+    async ({ contents }) => patchCode(contents, await getRule(buildOpts))
   );
 }
+
+export async function getRule(buildOpts: BuildOptions) {
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/load-instrumentation.ts:21]: Inject `instrumentationFilePath: string | null` to simplify the testing

**Review by vicb — CHANGES_REQUESTED** [review]
Thanks!

I have added a few comments

File: examples/common/apps.ts (hunk 1 above)
Comment (vicb) [reply examples/common/apps.ts:10]: Oh probably because this is in Next15...

Does instrumentation work on Next14?

Maybe we should have a playground14 and a playground15?

File: examples/middleware/tsconfig.json (hunk 2 above)
Comment (dario-piotrowicz) [reply examples/middleware/tsconfig.json]: I made this change by mistake, I was sure I reverted it but I forgot to push the change up, done, thanks for noticing it 👍

**Comment by dario-piotrowicz** [comment]
converted to draft as I just noticed that the patch does not work on Next 14

File: examples/common/apps.ts (hunk 1 above)
Comment (dario-piotrowicz) [reply examples/common/apps.ts]: done

File: examples/common/apps.ts [hunk 4]
```diff
@@ -3,7 +3,8 @@ const apps = [
   // examples
   "create-next-app",
   "middleware",
-  "playground",
+  "playground14",
+  "playground15",
```
Comment (vicb) [inline examples/common/apps.ts:7]: Thanks 🙏

File: examples/middleware/tsconfig.json
Comment (vicb) [inline examples/middleware/tsconfig.json:1]: Can you revert the permission change?

File: examples/playground14/app/api/instrumentation/route.ts [hunk 5]
```diff
@@ -0,0 +1,10 @@
+import { NextResponse } from "next/server";
+
+export const dynamic = "force-dynamic";
+
+export function GET() {
+  return NextResponse.json({
+    "nodejs-instrumentation-setup": globalThis["__NODEJS_INSTRUMENTATION_SETUP"] ?? "undefined",
```
Comment (vicb) [inline examples/playground14/app/api/instrumentation/route.ts:7]: is `?? "undefined"` really needed?

File: examples/playground15/README.md
Comment (vicb) [inline examples/playground15/README.md:1]: Remove this file?

File: packages/cloudflare/src/cli/build/patches/plugins/load-instrumentation.spec.ts [hunk 6]
```diff
@@ -1,48 +1,61 @@
-import { describe, expect, test } from "vitest";
+import { describe, expect, test, vi } from "vitest";
 
 import { patchCode } from "../ast/util.js";
-import { instrumentationRule } from "./load-instrumentation.js";
+import { getRule } from "./load-instrumentation.js";
+
+vi.mock(import("node:fs"), async (importOriginal) => {
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/load-instrumentation.spec.ts:6]: remove?

File: packages/cloudflare/src/cli/build/patches/plugins/load-instrumentation.ts [hunk 7]
```diff
@@ -2,23 +2,34 @@
...
-export function patchLoadInstrumentation(updater: ContentUpdater) {
   return updater.updateContent(
     "patch-load-instrumentation",
     { filter: /\.(js|mjs|cjs|jsx|ts|tsx)$/, contentFilter: /async loadInstrumentationModule\(/ },
-    ({ contents }) => patchCode(contents, instrumentationRule)
+    async ({ contents }) => patchCode(contents, await getRule(builtInstrumentationPath))
   );
 }
+
+export async function getRule(builtInstrumentationPath: string | null) {
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/load-instrumentation.ts:21]: remove async + corresponding awaits (also in test)

File: examples/playground14/app/api/instrumentation/route.ts (hunk 5 above)
Comment (dario-piotrowicz) [reply examples/playground14/app/api/instrumentation/route.ts:7]: no, but without it you would not get the field at all, for making this more self-explanatory I find it nice to clearly include "undefined" instead, but if you prefer the other version I'll switch to it

File: packages/cloudflare/src/cli/build/patches/plugins/instrumentation.ts [hunk 8]
```diff
@@ -0,0 +1,84 @@
...
+      "patch-load-instrumentation",
+      { filter: /\.(js|mjs|cjs|jsx|ts|tsx)$/, contentFilter: /async loadInstrumentationModule\(/ },
+      async ({ contents }) => patchCode(contents, getNext15Rule(builtInstrumentationPath))
+    ),
+    updater.updateContent(
+      "patch-prepareImpl",
+      { filter: /\.(js|mjs|cjs|jsx|ts|tsx)$/, contentFilter: /async prepareImpl\(/ },
+      async ({ contents }) => patchCode(contents, getNext14Rule(builtInstrumentationPath))
+    ),
+  ];
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/instrumentation.ts:23]: We do not need to return 2 plugins, they are just "fake" plugins anyway

```suggestion
  updater.updateContent(
    "patch-instrumentation-next15",
    { filter: /\.(js|mjs|cjs|jsx|ts|tsx)$/, contentFilter: /async loadInstrumentationModule\(/ },
    async ({ contents }) => patchCode(contents, getNext15Rule(builtInstrumentationPath))
  );
  
  updater.updateContent(
    "patch-instrumentation-next14",
    { filter: /\.(js|mjs|cjs|jsx|ts|tsx)$/, contentFilter: /async prepareImpl\(/ },
    async ({ contents }) => patchCode(contents, getNext14Rule(builtInstrumentationPath))
  );

  return {
    "patch implementation",
    setup() {},
  };
```

File: packages/cloudflare/src/cli/build/patches/plugins/instrumentation.ts [hunk 9]
```diff
@@ -0,0 +1,84 @@
...
+        }
+  `;
+}
+
+/**
+ * Gets the instrumentation.js file that the Next.js build process generates when an
+ * instrumentation hook is provided in the app's source
+ *
+ * @param buildOpts the open-next build options
+ * @returns a string pointing to the instrumentation.js file location, or null if such file is not found
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/instrumentation.ts:65]: maybe shorten this as the comment is already quite detailed?
```suggestion
 * @returns the path to the instrumentation.js, or null if it doesn't exist
```

File: packages/cloudflare/src/cli/build/bundle-server.ts [hunk 10]
```diff
@@ -91,7 +91,7 @@ export async function bundleServer(buildOpts: BuildOptions): Promise<void> {
       setWranglerExternal(),
       fixRequire(updater),
       handleOptionalDependencies(optionalDependencies),
-      patchLoadInstrumentation(updater),
+      ...patchInstrumentation(updater, buildOpts),
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/bundle-server.ts:94]: With my suggestion in the patch file
```suggestion
      patchInstrumentation(updater, buildOpts),
```

File: packages/cloudflare/src/cli/build/patches/plugins/instrumentation.ts [hunk 11]
```diff
@@ -0,0 +1,84 @@
...
+ */
+function getBuiltInstrumentationPath(buildOpts: BuildOptions): string | null {
+  const { outputDir } = buildOpts;
+
+  const baseDir = join(outputDir, "server-functions/default", getPackagePath(buildOpts));
+  const dotNextDir = join(baseDir, ".next");
+  const maybeBuiltInstrumentationPath = join(dotNextDir, "server", `${INSTRUMENTATION_HOOK_FILENAME}.js`);
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/instrumentation.ts:72]: maybe?
```suggestion
  const maybeBuiltInstrumentationPath = join(outputDir, "server-functions/default", getPackagePath(buildOpts), `.next/server/${INSTRUMENTATION_HOOK_FILENAME}.js` );
```

File: packages/cloudflare/src/cli/build/patches/plugins/instrumentation.ts [hunk 12]
```diff
@@ -0,0 +1,84 @@
...
+  const builtInstrumentationPath = existsSync(maybeBuiltInstrumentationPath)
+    ? maybeBuiltInstrumentationPath
+    : null;
+
+  return builtInstrumentationPath;
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/instrumentation.ts:77]:
```suggestion
  return existsSync(maybeBuiltInstrumentationPath)
    ? maybeBuiltInstrumentationPath
    : null;
```

File: examples/playground14/e2e/playwright.dev.config.ts
[the remark this answers is not in the document]
Comment (dario-piotrowicz) [reply examples/playground14/e2e/playwright.dev.config.ts:1]: ah I see, the value here is that this is testing that `getCloudflareContext` also works in dev, do you think that that isn't worth testing?

**Review by vicb — APPROVED** [review]
Awesome, thanks!

File: examples/playground14/e2e/playwright.dev.config.ts
[the remark this answers is not in the document]
Comment (vicb) [reply examples/playground14/e2e/playwright.dev.config.ts:1]: Oh yes, you're right, it makes complete sense now that the example is the full playground. My brain hadn't updated yet :)
