### PR TITLE
patch `require("react-dom/server.edge")` calls in `pages.runtime.prod.js` so that they are `try-catch`ed

### LINKED ISSUE #119: Could not resolve "react-dom/server.edge"
Im trying to deploy my nextj app but it is not working

package.json
```json
{
    "name": "awesome-project",
    "version": "0.1.0",
    "private": true,
    "scripts": {
        "build:worker": "cloudflare",
        "dev:worker": "wrangler dev --port 8771",
        "preview:worker": "npm run build:worker && npm run dev:worker",
        "deploy:worker": "npm run build:worker && wrangler deploy"
    },
    "dependencies": {
        "next": "^15.0.2",
        "react": "^18.3.1",
        "react-dom": "^18.3.1"
    },
    "devDependencies": {
        "@opennextjs/cloudflare": "^0.2.1",
        "@types/node": "^22",
        "@types/react": "^18",
        "@types/react-dom": "^18",
        "eslint": "^8",
        "eslint-config-next": "15.0.2",
        "next-translate-plugin": "^2.6.2",
        "postcss": "^8",
        "prettier": "^3.3.3",
        "prettier-plugin-svelte": "^3.2.7",
        "prettier-plugin-tailwindcss": "^0.6.8",
        "tailwindcss": "^3.4.1",
        "typescript": "^5",
        "wrangler": "^3.84.1"
    }
}
```
Im trying to deploy the server with `npm run deploy:worker` and here is the log

log
```
✘ [ERROR] Build failed with 1 error:

  ✘ [ERROR] Could not resolve "react-dom/server.edge"
  
  
  .worker-next/.next/standalone/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:14:16350:
        14 │ ...";e.exports=require("react-dom/server.edge")},path:e=>{"use str...
           ╵                        ~~~~~~~~~~~~~~~~~~~~~~~
  
    The path "./server.edge" is not exported by package "react-dom":
  
      .worker-next/.next/standalone/node_modules/react-dom/package.json:39:13:
        39 │   "exports": {
           ╵              ^
  
  You can mark the path "react-dom/server.edge" as external to exclude it from the bundle, which
  will remove this error. You can also surround this "require" call with a try/catch block to handle
  this failure at run-time instead of bundle-time.
  ```

Is there anything I did wrong or it is not related to opennextjs-cloudflare

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
wrap `require("react-dom/server.edge")` calls in `pages.runtime.prod.js` in `try-catch`es so that esbuild won't fail when encountering them, this doesn't guarantee that things won't blow up at runtime though

___

fixes #119

### CODE REVIEW

File: packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts [hunk 1]
```diff
@@ -23,6 +26,8 @@ export function patchWranglerDeps(config: Config) {
 
   writeFileSync(pagesRuntimeFile, patchedPagesRuntime);
 
+  patchRequireReactDomServerEdge(config);
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts:29]: q: should this be a different patch so that we can better assert if it's (or the existing patchWranglerDeps) patch is applied?

File: packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts [hunk 2]
```diff
@@ -67,3 +72,116 @@ function getDistPath(config: Config): string {
...
+    if (p.length !== 1) {
+      return;
+    }
+    const parameterName = p[0]!.getName();
+    const bodyChildren = arrowFunction.getBody().getChildren();
+    if (
+      bodyChildren.length !== 3 ||
+      bodyChildren[0]!.getFullText() !== "{" ||
+      bodyChildren[2]!.getFullText() !== "}"
+    ) {
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts:113]: nit: I find the following easier to read

```suggestion
    if (!(
      bodyChildren.length === 3 &&
      bodyChildren[0]!.getFullText() === "{" &&
      bodyChildren[2]!.getFullText() === "}"
    )) {
```

File: packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts [hunk 3]
```diff
@@ -67,3 +72,116 @@ function getDistPath(config: Config): string {
...
+      return;
+    }
+    const bodyStatements = bodyChildren[1]?.getChildren();
+
+    // the function has only two statements: "use strict" and e.exports=require("react-dom/server.edge")
+    if (
+      bodyStatements?.length !== 2 ||
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts:120]: same idea here

**Review by vicb — APPROVED** [review]
Thanks, looks good!

A few nits ;)

File: packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts (hunk 1 above)
Comment (dario-piotrowicz) [reply packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts:29]: this patches the `.next/standalone/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js` file, which is already being patched by the `patchWranglerDeps` function, so I tough it was correct to include it here, I don't have any preference on where to include this logic this just seemed the most natural and consistent place right now

I'm actually not sure, `patchWranglerDeps` patches multiple unrelated things/files, shouldn't those also be their own separate patch functions?

File: packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts (hunk 2 above)
Comment (dario-piotrowicz) [reply packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts:113]: I personally find my version easier to read, but I'm happy to use your version if that's what you prefer 🙂

File: packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts [hunk 4]
```diff
@@ -107,18 +107,22 @@ function patchRequireReactDomServerEdge(config: Config) {
     const parameterName = p[0]!.getName();
     const bodyChildren = arrowFunction.getBody().getChildren();
     if (
-      bodyChildren.length !== 3 ||
-      bodyChildren[0]!.getFullText() !== "{" ||
-      bodyChildren[2]!.getFullText() !== "}"
+      !(
+        bodyChildren.length === 3 &&
+        bodyChildren[0]!.getFullText() === "{" &&
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts:112]: I had approved your version, you could have kept it. 
Curious if you can remove the ! here and below now

Comment (dario-piotrowicz) [reply packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts:112]: > I had approved your version, you could have kept it.

it's all good 🙂👍 


> Curious if you can remove the ! here and below now

No
Screenshot 2025-01-08 at 17 48 17

File: packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts (hunk 1 above)
Comment (dario-piotrowicz) [reply packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts:29]: @vicb I'm happy to merge but please let me know about the above, I am happy with whatever solution you prefer 🙂

Comment (vicb) [reply packages/cloudflare/src/cli/build/patches/to-investigate/wrangler-deps.ts:29]: Merge it 🚀
We can always update later if needed
