### PR TITLE
Define `process.version` and `process.versions.node`

### LINKED ISSUE #333: [BUG] Error: Invariant: renderHTML should not be called in minimal mode
### Describe the bug

I'm trying to make a post to the following NextJS API route and get this error back after the wrangler / opennext build. Not sure what's causing it

```
import { NextRequest, NextResponse } from 'next/server';
import { isValidHandle } from '@atproto/syntax'

import { client as atprotoOauthClient } from '@/lib/atproto/oauth/client'

type Session = { did: string }

export async function POST(req: NextRequest) {
  const data = await req.json()

  // Validate
  const handle = data.handle
  if (typeof handle !== 'string' || !isValidHandle(handle)) {
    return NextResponse.json({error: "invalid handle"})
  }

  // Initiate the OAuth flow
  try {
    const url = await atprotoOauthClient.authorize(handle, {
      scope: 'atproto transition:generic',
    })
    return NextResponse.json({ redirect: url.toString() })
  } catch (err) {
    return NextResponse.json({error: "oauth authorize failed", details: err, message: err.message})
  }
}
```

### Steps to reproduce

Not sure yet, can get CF trace details

I can see about producing a minimal reproducer in the next couple of days

### Expected behavior

I can post to oauth endpoint and not get errors

### @opennextjs/cloudflare version

0.5.3

### Wrangler version

3.109.2

### next info output

```shell
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.3.0: Thu Jan  2 20:23:36 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T8112
  Available memory (MB): 24576
  Available CPU cores: 8
Binaries:
  Node: 21.7.1
  npm: 10.5.0
  Yarn: 1.22.21
  pnpm: 8.14.0
Relevant Packages:
  next: 15.1.7 // Latest available version is detected (15.1.7).
  eslint-config-next: 15.1.0
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.3
Next.js Config:
  output: standalone
```

### Additional context

running site is at https://verdverm.verdverm.workers.dev

### PR DESCRIPTION
**Pull request by vicb**
fixes #333 

Jose (and other packages) relies on `process.version` and `process.versions.node`.

Defining them here until https://github.com/unjs/unenv/pull/493 is merged

/cc @petebacondarwin @mhart

### CODE REVIEW

**Review by james-elicx — APPROVED** [review]

File: packages/cloudflare/src/cli/templates/worker.ts [hunk 1]
```diff
@@ -67,6 +68,13 @@ function populateProcessEnv(url: URL, env: CloudflareEnv) {
   if (processEnvPopulated) {
     return;
   }
+
+  // Some packages rely on `process.version` and `process.versions.node` (i.e. Jose@4)
+  // TODO: Remove when https://github.com/unjs/unenv/pull/493 is merged
+  Object.assign(process, { version: process.version || "v22.14.0" });
```
Comment (conico974) [inline packages/cloudflare/src/cli/templates/worker.ts:74]: I'm wondering if this should be customizable. For this specific use case it's fine, but maybe some other libs may need a different version. 
By default it is `22.14` but could be set to whatever the user may need

Comment (james-elicx) [reply packages/cloudflare/src/cli/templates/worker.ts:74]: IMO the libraries depending on process.version is an issue itself that they should seek to address. I believe jose no longer depends on process.version in its newer versions, and rightly so considering there are many non-node runtimes that it would be impossible to give a realistic value for...

Comment (conico974) [reply packages/cloudflare/src/cli/templates/worker.ts:74]: Totally agree, but since we can't control that, i think a customizable option is the best we can do

Comment (sommeeeer) [reply packages/cloudflare/src/cli/templates/worker.ts:74]: Could probably have a temporary env variable to customize it just in case. Since this will be removed once that PR gets merged anyways.

Comment (vicb) [reply packages/cloudflare/src/cli/templates/worker.ts:74]: > I'm wondering if this should be customizable. For this specific use case it's fine, but maybe some other libs may need a different version.

I'm on the fence here...
Being able to customize the version  might help but then what happens if there are conflicting libs?
If we use a fixed version, we will get bug reports if some packages need a different version and we could start logging that.

> Could probably have a temporary env variable to customize it just in case. Since this will be removed once that PR gets merged anyways.

Well, the unenv PR sets this to 22.14 as well.

Comment (conico974) [reply packages/cloudflare/src/cli/templates/worker.ts:74]: > If we use a fixed version, we will get bug reports if some packages need a different version and we could start logging that.

To be fair, we will likely get bug report even if we have the option to customize (and we could add a comment alongside to post issues related to that). And at least there will be a fix for these cases not involving another lib

As for the conflicting libs, there is not much we can do in these cases anyway with this (having a fixed version won't help either)

Comment (vicb) [reply packages/cloudflare/src/cli/templates/worker.ts:74]: We will probably have a fixed version in `unenv` (see the PR linked in the description).

So I'm +1 to merge as is and update if later if needed. Having knobs means documentation, maintenance, ... I would like to avoid this if possible.

Comment (conico974) [reply packages/cloudflare/src/cli/templates/worker.ts:74]: Fine by me, let's merge as is

**Review by conico974 — APPROVED** [review]

File: packages/cloudflare/src/cli/templates/worker.ts (hunk 1 above)
Comment (vicb) [reply packages/cloudflare/src/cli/templates/worker.ts:74]: 🤞

**Comment by vicb** [comment]
Thanks for the feedback!
Let's merge and see how it goes.
