### PR TITLE
fix: vercel og patch not moving to right node_modules directory

### LINKED ISSUE #376: [BUG] copyFile no such file node_modules/next/dist/compiled/@vercel/og/index.edge.js
### Describe the bug

after udpate to 0.5.0

using `npm run preview:worker`

```
node:fs:3003
binding.copyFile(
Error: ENOENT: no such file or directory, copyfile 'xxx/node_modules/next/dist/compiled/@vercel/og/index.edge.js' -> 'xxx/.open-next/server-functions/default/xxx/node_modules/next/dist/compiled/@vercel/og/index.edge.js'
at copyFileSync (node:fs:3003:11)
at patchVercelOgLibrary (file:///xxx/node_modules/@opennextjs/cloudflare/dist/cli/build/patches/ast/patch-vercel-og-library.js:25:13)
at bundleServer (file:///xxx/node_modules/@opennextjs/cloudflare/dist/cli/build/bundle-server.js:44:5)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async build (file:///xxx/node_modules/@opennextjs/cloudflare/dist/cli/build/build.js:71:5)
at async file:///xxx/node_modules/@opennextjs/cloudflare/dist/cli/index.js:7:1 {
 errno: -2,
code: 'ENOENT',
syscall: 'copyfile',
path: '/xxx/node_modules/next/dist/compiled/@vercel/og/index.edge.js',
dest: '/xxx/.open-next/server-functions/default/xxx/node_modules/next/dist/compiled/@vercel/og/index.edge.js'
}

Node.js v20.10.0
```

### Steps to reproduce
```
git clone https://github.com/j4tmr/copyfile-error
cd copyfile-error
npm install
cd apps/web
npm run preview
```

### Expected behavior

-

### @opennextjs/cloudflare version

0.5.0

### Wrangler version

3.108.1

### next info output

```shell
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:16 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6000
  Available memory (MB): 65536
  Available CPU cores: 10
Binaries:
  Node: 20.10.0
  npm: 10.9.2
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 15.1.7 // Latest available version is detected (15.1.7).
  eslint-config-next: 15.1.7
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.2
Next.js Config:
  output: N/A
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by james-elicx**
fixes #376 

In some monorepo projects when running build there is a node_modules inside `server-functions` but not inside `server-functions/{projectPath}`.

This change to check for the existence of the package-scoped node_modules before choosing it over the non-package-scoped one.

Not quite sure how simple it would be to add an e2e for this because it's dependent on the monorepo structure and I believe it would be hit for us due to having multiple apps

### CODE REVIEW

File: packages/cloudflare/src/cli/build/patches/ast/patch-vercel-og-library.ts [hunk 1]
```diff
@@ -55,3 +58,12 @@ export function patchVercelOgLibrary(buildOpts: BuildOptions) {
     writeFileSync(routeFilePath, node.commitEdits(edits));
   }
 }
+
+function getOutputDir(opts: { functionsPath: string; packagePath: string }) {
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/ast/patch-vercel-og-library.ts:62]:
```suggestion
function getOutputDir({ functionsPath: string; packagePath: string }) {
```

File: packages/cloudflare/src/cli/build/patches/ast/patch-vercel-og-library.ts [hunk 2]
```diff
@@ -10,6 +10,8 @@ import { patchVercelOgFallbackFont, patchVercelOgImport } from "./vercel-og.js";
 
 type TraceInfo = { version: number; files: string[] };
 
+const vercelOgNodeModulePath = "node_modules/next/dist/compiled/@vercel/og";
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/ast/patch-vercel-og-library.ts:13]: move that to getOutputDir?

File: packages/cloudflare/src/cli/build/patches/ast/patch-vercel-og-library.ts [hunk 3]
```diff
@@ -18,15 +18,16 @@ type TraceInfo = { version: number; files: string[] };
...
+  const packagePath = path.join(functionsPath, getPackagePath(buildOpts));
 
   for (const traceInfoPath of globSync(path.join(appBuildOutputPath, ".next/server/**/*.nft.json"))) {
     const traceInfo: TraceInfo = JSON.parse(readFileSync(traceInfoPath, { encoding: "utf8" }));
     const tracedNodePath = traceInfo.files.find((p) => p.endsWith("@vercel/og/index.node.js"));
 
     if (!tracedNodePath) continue;
 
-    const outputDir = path.join(packagePath, "node_modules/next/dist/compiled/@vercel/og");
+    const outputDir = getOutputDir({ functionsPath, packagePath });
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/ast/patch-vercel-og-library.ts:30]: question: could this be derived from the location of the trace file?

Comment (james-elicx) [reply packages/cloudflare/src/cli/build/patches/ast/patch-vercel-og-library.ts:30]: not from the nft files from what i saw unless i missed something. the existence check could be changed to be checking if the normal package directory's node_modules contains it (apps/web/node_modules), but i stuck to doing the existence check on our output directory instead of their project's directory.

Comment (vicb) [reply packages/cloudflare/src/cli/build/patches/ast/patch-vercel-og-library.ts:30]: Thanks for the explanation.

_(If we drop copying the traced files as mentioned yesterday, we wouldn't even have to copy...)_

**Review by vicb — APPROVED** [review]
Oops forgot to approve!

Thanks James for the quick fix 🙏
