### PR TITLE
fix: invalid paths in windows bundles

### LINKED ISSUE #204: [BUG] Windows Build Failing: Could not resolve open-nextserver-functionsdefaultcache.cjs
### Describe the bug

When attempting to deploy the [firelabs-net/workers-next](https://github.com/flarelabs-net/workers-next) template and having made no changes to the template, the `npm run deploy` fails.  Specifically the `wrangler deploy` step fails. 

This is happening on a Windows machine in standard PowerShell terminal as well as WSL Ubuntu and Debian. 

```
✘ [ERROR] Build failed with 1 error:

  ✘ [ERROR] Could not resolve
  "C:Users\tdesmondProjects\tempempty-hall-5379.open-nextserver-functionsdefaultcache.cjs"

      .open-next/server-functions/default/handler.mjs:30791:39:
        30791 │ ...= require('C:\Users\tdesmond\Projects\temp\empty-hall-5379\....
              ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    You can mark the path
  "C:Users\tdesmondProjects\tempempty-hall-5379.open-nextserver-functionsdefaultcache.cjs" as
  external to exclude it from the bundle, which will remove this error. You can also surround this
  "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
``` 

### Steps to reproduce

1. On a Windows machine create new Next.js project based on the 0.3 build `npm create cloudflare@latest -- --template https://github.com/flarelabs-net/workers-next`
2. Attempt to deploy the application `npm run deploy`

### Expected behavior

I'm expecting `npm run deploy` to complete without errors and deploy my application to Workers Assets. 

### @opennextjs/cloudflare version

0.3

### Wrangler version

3.99.0

### next info output

```shell
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32206
  Available CPU cores: 22
Binaries:
  Node: 20.16.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 14.2.5 // An outdated version detected (latest is 15.1.2), upgrade is highly recommended!
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.7.2
Next.js Config:
  output: N/A
 ⚠ An outdated version detected (latest is 15.1.2), upgrade is highly recommended!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

### Additional context

_No response_

### LINKED ISSUE #236: windows support
Reports from various people/channels that Windows has issues.
- figure out (investigate) what the problem areas are
- fix issues that come up
- update docs where applicable

### PR DESCRIPTION
**Pull request by james-elicx**
Changes some instances of inlined paths to use the normalizePath helper (the cache one was the main problem) and updates an esbuild filter.

Bumps aws package to use the prerelease in https://github.com/opennextjs/opennextjs-aws/pull/695 to fix the esbuild filters.

fixes #204
fixes #236

### CODE REVIEW

File: packages/cloudflare/src/cli/build/open-next/createServerBundle.ts [hunk 1]
```diff
@@ -17,6 +17,8 @@ import { openNextReplacementPlugin } from "@opennextjs/aws/plugins/replacement.j
 import { openNextResolvePlugin } from "@opennextjs/aws/plugins/resolve.js";
 import type { FunctionOptions, SplittedFunctionOptions } from "@opennextjs/aws/types/open-next.js";
 
+import { normalizePath } from "../utils/index.js";
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/open-next/createServerBundle.ts:20]: would be nice to upstream those changes to aws

**Review by vicb — APPROVED** [review]
Awesome, thank you so much!
