### PR TITLE
fix res.revalidate

### LINKED ISSUE #463: [BUG] Fix `res.revalidate`
In pages router, `res.revalidate()` doesn't work. It throws an exception.
It probably needs to be patched to use the `NEXT_CACHE_REVALIDATION_WORKER` binding instead of calling itself

### PR DESCRIPTION
**Pull request by conico974**
Fixes #463

### CODE REVIEW

File: packages/cloudflare/src/cli/build/patches/plugins/res-revalidate.ts [hunk 1]
```diff
@@ -0,0 +1,78 @@
+import { patchCode } from "@opennextjs/aws/build/patch/astCodePatcher.js";
```
Comment (vicb) [inline packages/cloudflare/src/cli/build/patches/plugins/res-revalidate.ts:1]: Can you add a file level comment describing what the patch does (i.e. use `NEXT_CACHE_REVALIDATION_WORKER` to fetch).

**Review by vicb — APPROVED** [review]
Thanks.

LGTM.  

Could you please add a file level comment for the patch?

**Comment by vicb** [comment]
Thanks for the update!
